version: '2'
services:
    nginx:
        build: ./docker/nginx/
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - php
            - maridb
    php:
        build: ./docker/php/
        volumes:
            - ./:/var/www
    maridb:
        image: mariadb:10.1
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=world"
        ports:
            - "33061:3306"
        volumes:
            - ./docker/mariadb/data:/var/lib/mysql
        container_name: worldmariadb